package com.tmm.mall.mapper;

import com.tmm.mall.model.SmsCouponHistory;
import com.tmm.mall.model.SmsCouponHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SmsCouponHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    long countByExample(SmsCouponHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int deleteByExample(SmsCouponHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int insert(SmsCouponHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int insertSelective(SmsCouponHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    List<SmsCouponHistory> selectByExample(SmsCouponHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    SmsCouponHistory selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int updateByExampleSelective(@Param("record") SmsCouponHistory record, @Param("example") SmsCouponHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int updateByExample(@Param("record") SmsCouponHistory record, @Param("example") SmsCouponHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int updateByPrimaryKeySelective(SmsCouponHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    int updateByPrimaryKey(SmsCouponHistory record);
}