package com.tmm.mall.model;

import java.io.Serializable;
import java.util.Date;

public class SmsCouponHistory implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.coupon_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Long couponId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.member_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Long memberId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.coupon_code
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private String couponCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.member_nickname
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private String memberNickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.get_type
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Integer getType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.create_time
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.use_status
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Integer useStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.use_time
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Date useTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.order_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private Long orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sms_coupon_history.order_sn
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private String orderSn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.id
     *
     * @return the value of sms_coupon_history.id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.id
     *
     * @param id the value for sms_coupon_history.id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.coupon_id
     *
     * @return the value of sms_coupon_history.coupon_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Long getCouponId() {
        return couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.coupon_id
     *
     * @param couponId the value for sms_coupon_history.coupon_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setCouponId(Long couponId) {
        this.couponId = couponId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.member_id
     *
     * @return the value of sms_coupon_history.member_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Long getMemberId() {
        return memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.member_id
     *
     * @param memberId the value for sms_coupon_history.member_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setMemberId(Long memberId) {
        this.memberId = memberId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.coupon_code
     *
     * @return the value of sms_coupon_history.coupon_code
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public String getCouponCode() {
        return couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.coupon_code
     *
     * @param couponCode the value for sms_coupon_history.coupon_code
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setCouponCode(String couponCode) {
        this.couponCode = couponCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.member_nickname
     *
     * @return the value of sms_coupon_history.member_nickname
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public String getMemberNickname() {
        return memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.member_nickname
     *
     * @param memberNickname the value for sms_coupon_history.member_nickname
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setMemberNickname(String memberNickname) {
        this.memberNickname = memberNickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.get_type
     *
     * @return the value of sms_coupon_history.get_type
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Integer getGetType() {
        return getType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.get_type
     *
     * @param getType the value for sms_coupon_history.get_type
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setGetType(Integer getType) {
        this.getType = getType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.create_time
     *
     * @return the value of sms_coupon_history.create_time
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.create_time
     *
     * @param createTime the value for sms_coupon_history.create_time
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.use_status
     *
     * @return the value of sms_coupon_history.use_status
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.use_status
     *
     * @param useStatus the value for sms_coupon_history.use_status
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.use_time
     *
     * @return the value of sms_coupon_history.use_time
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Date getUseTime() {
        return useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.use_time
     *
     * @param useTime the value for sms_coupon_history.use_time
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setUseTime(Date useTime) {
        this.useTime = useTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.order_id
     *
     * @return the value of sms_coupon_history.order_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public Long getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.order_id
     *
     * @param orderId the value for sms_coupon_history.order_id
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setOrderId(Long orderId) {
        this.orderId = orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sms_coupon_history.order_sn
     *
     * @return the value of sms_coupon_history.order_sn
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public String getOrderSn() {
        return orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sms_coupon_history.order_sn
     *
     * @param orderSn the value for sms_coupon_history.order_sn
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    public void setOrderSn(String orderSn) {
        this.orderSn = orderSn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sms_coupon_history
     *
     * @mbg.generated Wed Feb 26 23:44:16 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", couponId=").append(couponId);
        sb.append(", memberId=").append(memberId);
        sb.append(", couponCode=").append(couponCode);
        sb.append(", memberNickname=").append(memberNickname);
        sb.append(", getType=").append(getType);
        sb.append(", createTime=").append(createTime);
        sb.append(", useStatus=").append(useStatus);
        sb.append(", useTime=").append(useTime);
        sb.append(", orderId=").append(orderId);
        sb.append(", orderSn=").append(orderSn);
        sb.append(", serialVersionUID=").append(serialVersionUID);
        sb.append("]");
        return sb.toString();
    }
}